# 📘 Exploring DataFrame Properties in Pandas (Telugu)

In this video, we’ll **deep dive into the important properties and internal structure of a Pandas DataFrame**.

We’ll cover:

- 📐 Shape, Size, Index, Columns
- 🔢 Dtypes, ndim, values, axes
- 🧠 Data inspection using info(), describe()
- ✅ How to access rows, columns, and cells using direct access, `.iloc`, and `.loc`
- 💾 Memory usage & summary

Let’s understand each one practically!

In [ ]:
# Step 1: Import pandas
import pandas as pd

## ✅ Create a Sample DataFrame

1.   List item
2.   List item



We’ll use a small dataset for easy understanding.

In [ ]:
data = {
    'Name': ['Joe', 'John', 'Shane'],
    'Subject': ['Maths', 'Science', 'English'],
    'Marks': [85, 91, 78],
    'Passed': [True, True, False]
}

df = pd.DataFrame(data)
df

    Name  Subject  Marks  Passed
0    Joe    Maths     85    True
1   John  Science     91    True
2  Shane  English     78   False

## 📐 Basic Structure

Let’s see the most basic info about rows and columns.

In [ ]:
# Shape → (rows, columns)
df.shape

(3, 4)

In [ ]:
# Size → Total number of elements (rows * columns)
df.size

12

In [ ]:
# ndim → Number of dimensions (should be 2 for DataFrame)
df.ndim

2

## 🏷️ Labels and Metadata

In [ ]:
# Index → Row labels
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
# Columns → Column labels
df.columns

Index(['Name', 'Subject', 'Marks', 'Passed'], dtype='object')

In [ ]:
# Axes → Returns both row and column labels
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['Name', 'Subject', 'Marks', 'Passed'], dtype='object')]

## 🔢 Data Types & Internal Values

In [ ]:
# dtypes → Datatype of each column
df.dtypes

Name       object
Subject    object
Marks       int64
Passed       bool
dtype: object

In [ ]:
# values → Numpy array of all data
df.values

array([['Joe', 'Maths', 85, True],
       ['John', 'Science', 91, True],
       ['Shane', 'English', 78, False]], dtype=object)

## 🧠 Data Inspection Tools

These are used to understand large datasets quickly.

In [ ]:
# info() → Structure, non-null count, datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      object
 1   Subject  3 non-null      object
 2   Marks    3 non-null      int64
 3   Passed   3 non-null      bool
dtypes: bool(1), int64(1), object(2)
memory usage: 207.0+ bytes

In [ ]:
# describe() → Statistics summary (numeric only)
df.describe()

           Marks
count   3.000000
mean   84.666667
std     6.506407
min    78.000000
25%    81.500000
50%    85.000000
75%    88.000000
max    91.000000

In [ ]:
# memory_usage() → Memory used by each column
df.memory_usage()

Index      132
Name        24
Subject     24
Marks       24
Passed       3
dtype: int64

## 🔍 Real Use: Find Datatype Issues

This is useful when cleaning or preparing data.

In [ ]:
# Check for object (string) columns
df.select_dtypes(include='object')

    Name  Subject
0    Joe    Maths
1   John  Science
2  Shane  English

In [ ]:
# Check for numeric columns
df.select_dtypes(include='bool')

   Passed
0    True
1    True
2   False

## 🔓 Accessing Data in a DataFrame

In [ ]:
# Access single column
df['Marks']

0    85
1    91
2    78
Name: Marks, dtype: int64

In [ ]:
# Access multiple columns
df[['Name', 'Marks']]

    Name  Marks
0    Joe     85
1   John     91
2  Shane     78

In [ ]:
df

    Name  Subject  Marks  Passed
0    Joe    Maths     85    True
1   John  Science     91    True
2  Shane  English     78   False

In [ ]:
# Access row by position using iloc
df.iloc[0:2]

   Name  Subject  Marks  Passed
0   Joe    Maths     85    True
1  John  Science     91    True

In [ ]:
# Access row by label using loc
df.loc[0:2]

    Name  Subject  Marks  Passed
0    Joe    Maths     85    True
1   John  Science     91    True
2  Shane  English     78   False

In [ ]:
# Access specific cell: 2nd row, 3rd column
df.iloc[1, 2]

np.int64(91)

In [ ]:
# Access specific cell by label
df.loc[2, 'Passed']

np.False_

In [ ]:
# Access multiple rows and columns
df.loc[0:2, ['Name', 'Subject']]

    Name  Subject
0    Joe    Maths
1   John  Science
2  Shane  English

## ✅ Summary

🔹 `.shape`, `.size`, `.ndim` → Structure  
🔹 `.index`, `.columns`, `.axes` → Labels  
🔹 `.dtypes`, `.values` → Data types & internal format  
🔹 `.info()`, `.describe()` → Dataset overview  
🔹 `.memory_usage()` → RAM used  

📌 These are the most important attributes to understand any DataFrame easily before moving on to filtering, grouping, and machine learning.

👏 Well done! Now you are ready to clean and filter data confidently in the next lesson.

# 🧠 Practice Exercises: DataFrame Properties & Access

Try these questions using the DataFrame you created:

1. What is the shape, size, and number of dimensions of your DataFrame?
2. List all column names and their data types.
3. Use `.info()` and explain what each line means.
4. How much memory does your DataFrame consume?
5. Select only numeric columns using `select_dtypes()`.
6. Access:
   - A single column
   - Two columns
   - The second row
   - A specific cell (row 2, column "Marks")
   - A slice of rows and columns using `.loc`
7. Use `.describe()` to analyze statistics for numeric data.

In [ ]:
# 1. What is the shape, size, and number of dimensions?
print("Shape:", df.shape)        # (3, 3) → 3 rows, 3 columns
print("Size:", df.size)          # 9 → Total elements (3x3)
print("Dimensions:", df.ndim)    # 2 → It's a 2D structure (rows & columns)

# 2. List all column names and their data types
print("Columns:", df.columns.tolist())        # ['Name', 'Marks', 'Grade']
print("Data Types:\n", df.dtypes)

# 3. Use .info() and explain each line
df.info()
# Explanation:
# - RangeIndex: Total number of rows.
# - Data columns: Total number of columns and names.
# - Non-null count: Number of non-missing values.
# - Dtype: Data type of each column.
# - Memory usage: Memory consumed by the DataFrame.

# 4. How much memory does it use?
print("Memory usage:")
print(df.memory_usage(deep=True))  # Deep shows object/string memory too

# 5. Select only numeric columns
numeric_df = df.select_dtypes(include='number')
print(numeric_df)

# 6. Access:
print("Single column:\n", df['Marks'])                     # One column
print("Two columns:\n", df[['Name', 'Marks']])             # Two columns
print("Second row:\n", df.iloc[1])                         # Second row (index 1)
print("Cell at row 2, column 'Marks':", df.loc[1, 'Marks'])  # Specific cell

# Access a slice of rows and columns
print("Slice using .loc:\n", df.loc[0:1, ['Name', 'Marks']])

# 7. Use .describe()
print("Summary Statistics:\n", df.describe())

Shape: (3, 4)
Size: 12
Dimensions: 2
Columns: ['Name', 'Subject', 'Marks', 'Passed']
Data Types:
 Name       object
Subject    object
Marks       int64
Passed       bool
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      object
 1   Subject  3 non-null      object
 2   Marks    3 non-null      int64
 3   Passed   3 non-null      bool
dtypes: bool(1), int64(1), object(2)
memory usage: 207.0+ bytes
Memory usage:
Index      132
Name       183
Subject    190
Marks       24
Passed       3
dtype: int64
   Marks
0     85
1     91
2     78
Single column:
 0    85
1    91
2    78
Name: Marks, dtype: int64
Two columns:
     Name  Marks
0    Joe     85
1   John     91
2  Shane     78
Second row:
 Name          John
Subject    Science
Marks           91
Passed        True
Name: 1, dtype: object
Cell at row 2, column 'Marks': 91
Slice using .loc:
    Name  Marks
0   Joe     85
1  John     91
Summary Statistics:
            Marks
count   3.000000
mean   84.666667
std     6.506407
min    78.000000
25%    81.500000
50%    85.000000
75%    88.000000
max    91.000000