📘 **Video 4: Filtering Data in Pandas (Telugu)**  
In this video, we’ll learn how to **filter data from real datasets** using Pandas — a powerful skill used in every data analysis project.

We'll cover:

🔹 Filter with Logical Conditions: `>`, `<`, `==`, `!=`  
🔹 Combine Conditions with `&` and `|`  
🔹 Filter Text Columns using `.str.contains()` and `.str.startswith()`  
🔹 Reset index after filtering  
🔹 Filter Boolean columns (`True` / `False`)   
🔹 Tips to Avoid Common Filtering Mistakes

Let’s dive into the dataset and filter data smartly using Pandas.

---

In [ ]:
# ✅ Step 1: Import Pandas
import pandas as pd

📂 **Step 2: Load Real-World Dataset**

We are using a sample student performance dataset.

In [ ]:
# Load CSV file
df = pd.read_csv('House_Rent_Dataset.csv')

# Preview the data
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

🔍 **Step 3: Filter Using Logical Conditions**

In [ ]:
df[df['Rent'] < 100000]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

🔗 **Step 4: Combining Multiple Conditions with & and |**

In [ ]:
df[(df['City']=='Kolkata') | (df['Rent'] > 10000) | (df['Area Locality'] == 'Bandel')]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

🔤 **Step 5: Filtering Text Columns using .str**

In [ ]:
df[df['Area Locality'].str.contains('d')]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
27,2022-06-25,2,6000,1000,Ground out of 3,Super Area,"Kodalia, Hooghly-Chinsurah",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
29,2022-06-25,2,12500,850,Ground out of 2,Super Area,"Rabindra Sarobar Area, Dhakuria",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
31,2022-06-26,2,15000,900,Ground out of 2,Carpet Area,"Project Kaikhali, Vip Road",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4737,2022-07-07,3,15000,1500,Lower Basement out of 2,Super Area,Almasguda,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4738,2022-07-06,2,17000,855,4 out of 5,Carpet Area,"Godavari Homes, Quthbullapur",Hyderabad,Unfurnished,Bachelors,2,Contact Agent
4740,2022-06-02,2,12000,1350,2 out of 2,Super Area,Old Alwal,Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner

🔁 **Step 6: Resetting Index After Filtering**

This is helpful to clean up the index after filtering.

In [ ]:
f = df[df['City'] == 'Hyderabad']
f.reset_index(inplace=True)
f

,index,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,3878,2022-06-28,4,75000,3800,3 out of 10,Carpet Area,"Financial District, Nanakram Guda",Hyderabad,Semi-Furnished,Bachelors/Family,4,Contact Agent
1,3879,2022-06-30,4,250000,4500,Ground out of 2,Carpet Area,Jubilee Hills,Hyderabad,Semi-Furnished,Family,4,Contact Agent
2,3880,2022-05-20,2,10000,1100,1 out of 3,Super Area,Meerpet,Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
3,3881,2022-07-10,3,60000,3200,1 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4,3882,2022-05-12,2,12000,647,2 out of 3,Super Area,Moti Nagar,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
864,4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
865,4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
866,4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
867,4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

🚫 **Common Mistakes to Avoid**

✅ Always wrap each condition in parentheses `()`  
✅ Use `&` and `|`, **not** `and`/`or`  
✅ Use `.str` functions only with string columns  
✅ Don’t forget to reset index if needed after filtering

# Practice Questions

These questions help you practice Pandas filtering using conditions, string matching, and logical operators.

---

1️⃣ Show listings with Rent less than ₹10,000

2️⃣ Filter listings that are Semi-Furnished

3️⃣ Show listings with more than 1 Bathroom

4️⃣ Show listings preferred by Bachelors only

5️⃣ Show listings from 'Salt Lake City'

6️⃣ Show Unfurnished listings with Rent below ₹8000

7️⃣ Show listings that are either in 'Dumdum Park' or 'South Dum Dum'

8️⃣ Show listings where Area Type is 'Carpet Area' and Floor starts with '1 out'

9️⃣ Show listings posted after 2022-06-01

🔟 Filter listings where Rent > ₹15,000 and reset the index after filtering

In [ ]:
# 1️⃣ Listings with Rent less than ₹10,000
df[df['Rent'] < 10000]

# 2️⃣ Listings that are Semi-Furnished
df[df['Furnishing Status'] == 'Semi-Furnished']

# 3️⃣ Listings with more than 1 Bathroom
df[df['Bathroom'] > 1]

# 4️⃣ Listings preferred by Bachelors only
df[df['Point of Contact'].str.contains('Bachelors', case=False, na=False)]

# 5️⃣ Listings from 'Salt Lake City'
df[df['Area Locality'].str.contains('Salt Lake City', case=False, na=False)]

# 6️⃣ Unfurnished listings with Rent below ₹8000
df[(df['Furnishing Status'] == 'Unfurnished') & (df['Rent'] < 8000)]

# 7️⃣ Listings in 'Dumdum Park' or 'South Dum Dum'
df[df['Area Locality'].isin(['Dumdum Park', 'South Dum Dum'])]

# 8️⃣ Listings with 'Carpet Area' and Floor starts with '1 out'
df[(df['Area Type'] == 'Carpet Area') & (df['Floor'].str.startswith('1 out', na=False))]

# 9️⃣ Listings posted after 2022-06-01
df[pd.to_datetime(df['Posted On']) > pd.to_datetime('2022-06-01')]

# 🔟 Listings with Rent > ₹15,000 and reset index
filtered = df[df['Rent'] > 15000].reset_index(drop=True)
filtered

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
1,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-06-07,2,26000,800,1 out of 2,Carpet Area,"Palm Avenue Kolkata, Ballygunge",Kolkata,Unfurnished,Bachelors,2,Contact Agent
3,2022-05-23,3,25000,1200,1 out of 4,Carpet Area,"Action Area 1, Rajarhat Newtown",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent
4,2022-06-01,3,40000,1286,1 out of 1,Carpet Area,New Town Action Area 1,Kolkata,Furnished,Bachelors/Family,2,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
2413,2022-07-06,2,17000,855,4 out of 5,Carpet Area,"Godavari Homes, Quthbullapur",Hyderabad,Unfurnished,Bachelors,2,Contact Agent
2414,2022-07-06,2,25000,1040,2 out of 4,Carpet Area,Gachibowli,Hyderabad,Unfurnished,Bachelors,2,Contact Owner
2415,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
2416,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
2417,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent