# 🎥 Video 5: Handling Missing Data in Pandas

In this lesson, we will explore how to handle missing values (NaN/null) in datasets using Pandas.

We'll cover:
- Detecting missing values
- Dropping missing rows/columns
- Filling missing data using mean, median, mode, or custom values
- Real practice on the Titanic dataset

In [ ]:
# ✅ Step 1: Import Pandas
import pandas as pd

### 📂 Step 2: Load the Titanic Dataset

We are using the Titanic dataset which contains missing values in columns like `Age`, `Cabin`, and `Embarked`.

In [ ]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### 🔍 Step 3: Check for Missing Values

Start by identifying where and how many missing values exist in your dataset.

In [ ]:
# Returns True for missing values
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [ ]:
# Total missing values column-wise
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
# Total missing values in entire dataset
df.isnull().sum().sum()

np.int64(866)

In [ ]:
# Percentage of missing values per column
(df.isnull().sum() / len(df)) * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

### 🧹 Step 4: Dropping Missing Data

Remove rows or columns that contain missing data.

In [ ]:
# Drop rows with ANY missing values
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
# Drop columns with ANY missing values
df.dropna(axis=1)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

In [ ]:
# Drop rows where 'Cabin' column is null
df.dropna(subset=['Cabin'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

### 🧪 Step 5: Filling Missing Data

Fill missing values with calculated or custom values.

In [ ]:
# Fill 'Age' with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [ ]:
# Fill 'Age' with median
df['Age'] = df['Age'].fillna(df['Age'].median())

In [ ]:
# Fill 'Embarked' with mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
# Fill 'Cabin' with a custom string
df['Cabin'] = df['Cabin'].fillna("No Info")

In [ ]:
# Forward fill (fill missing value with previous non-null)
df.fillna(method='ffill')

### 🧠 Practice Questions: Handling Missing Data (Titanic Dataset)

1️⃣ Show all rows where `Age` is null.

2️⃣ Drop all rows where `Cabin` is missing.

3️⃣ Fill missing `Age` values with the median.

4️⃣ Fill missing `Embarked` values with the most frequent value (mode).

5️⃣ Fill missing `Fare` values with 0.

6️⃣ Replace missing `Cabin` entries with the string "No Info".

7️⃣ Create a new column `Cabin_missing` that is `True` if `Cabin` is null, else `False`.

8️⃣ Fill all missing values in the DataFrame using forward fill (`ffill`).

9️⃣ Count the total number of missing values in the dataset.

🔟 Drop all columns that contain at least one missing value.

In [ ]:
# 1️⃣ Show all rows where Age is null
df[df['Age'].isnull()]

# 2️⃣ Drop all rows where Cabin is missing
df.dropna(subset=['Cabin'])

# 3️⃣ Fill missing Age values with the median
df['Age'] = df['Age'].fillna(df['Age'].median())

# 4️⃣ Fill missing Embarked values with the most frequent value (mode)
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# 5️⃣ Fill missing Fare values with 0
df['Fare'] = df['Fare'].fillna(0)

# 6️⃣ Replace missing Cabin entries with the string "No Info"
df['Cabin'] = df['Cabin'].fillna("No Info")

# 7️⃣ Create a new column Cabin_missing that is True if Cabin is null, else False
df['Cabin_missing'] = df['Cabin'].isnull()

# 8️⃣ Fill all missing values in the DataFrame using forward fill (ffill)
df.fillna(method='ffill')

# 9️⃣ Count the total number of missing values in the dataset
df.isnull().sum().sum()

# 🔟 Drop all columns that contain at least one missing value
df.dropna(axis=1)