# 🎥 Video 9: Sorting Data in Pandas

In this video, we'll learn how to **sort data** in Pandas using functions like `sort_values()` and `sort_index()`.

💡 **Why is this important?**

Sorting is very useful in Machine Learning and data analysis. It helps to:
- Organize the data
- Rank or filter top performers
- Prepare datasets in a meaningful order

---

In [ ]:
# ✅ Step 1: Import Required Libraries
import pandas as pd

## 📥 Step 2: Load Sample Dataset

We'll create a small student dataset.

In [ ]:
# Sample student dataset
data = {
    'Student_Name': ['Surya', 'Ravi', 'Anu', 'Divya', 'Kiran'],
    'Math_Score': [85, 92, 78, 90, 88],
    'Science_Score': [89, 95, 80, 85, 91],
    'English_Score': [86, 87, 83, 80, 89]
}

df = pd.DataFrame(data)
df.head()

  Student_Name  Math_Score  Science_Score  English_Score
0        Surya          85             89             86
1         Ravi          92             95             87
2          Anu          78             80             83
3        Divya          90             85             80
4        Kiran          88             91             89

---
## 🔍 Step 3: Sort by One Column

We use `sort_values()` to sort data by a specific column.

**Syntax:**  
`df.sort_values(by='column_name', ascending=True or False)`

In [ ]:
# Sort by Math_Score in ascending order
df.sort_values(by='Math_Score', ascending=True)

  Student_Name  Math_Score  Science_Score  English_Score
2          Anu          78             80             83
0        Surya          85             89             86
4        Kiran          88             91             89
3        Divya          90             85             80
1         Ravi          92             95             87

In [ ]:
# Sort by Science_Score in descending order
df.sort_values(by='Science_Score', ascending=False)

  Student_Name  Math_Score  Science_Score  English_Score
1         Ravi          92             95             87
4        Kiran          88             91             89
0        Surya          85             89             86
3        Divya          90             85             80
2          Anu          78             80             83

---
## 📌 Step 5: Sorting by Index

Use `sort_index()` when you want to sort by row numbers or labels.

In [ ]:
df.sort_index()

  Student_Name  Math_Score  Science_Score  English_Score
0        Surya          85             89             86
1         Ravi          92             95             87
2          Anu          78             80             83
3        Divya          90             85             80
4        Kiran          88             91             89

---
## 🧠 Step 6: Real-Life Use Case – Ranking Students

Let’s calculate each student’s total score and then sort them to rank.

In [ ]:
# Add Total_Score column
df['Total_Score'] = df['Math_Score'] + df['Science_Score'] + df['English_Score']

# Sort by Total_Score (high to low)
df_sorted = df.sort_values(by='Total_Score', ascending=False)
df_sorted

  Student_Name  Math_Score  Science_Score  English_Score  Total_Score
1         Ravi          92             95             87          274
4        Kiran          88             91             89          268
0        Surya          85             89             86          260
3        Divya          90             85             80          255
2          Anu          78             80             83          241

# 📝 Step 7: Practice Questions – Sorting Data

Try solving the following using `sort_values()` and `sort_index()`:

1. Who is the top scorer based on Total Score?
2. Who are the bottom 2 students in Math?
3. Rank students by their English Score in descending order.
4. Sort all students alphabetically by their name.
5. Sort students by Grade level and then by Math Score.
6. Who are the top 3 Science scorers?
7. Sort the dataset by Total Score and reset the index.
8. Find students with the same Total Score after sorting.
9. Sort the DataFrame by index in descending order.
10. Create a rank column for students based on Total Score (1 for top scorer).