# 🎥 Video 10: Merging and Joining DataFrames | Pandas in Telugu #10

In this video, we will learn:
- How to combine multiple DataFrames using `merge()` and `concat()`
- Different types of joins: inner, outer, left, right
- Merging using one or multiple columns
- How to align data from multiple sources for machine learning

In [ ]:
# ✅ Step 1: Import Pandas
import pandas as pd

## 📥 Step 2: Create Sample DataFrames
We'll simulate student information and test scores like in real ML datasets.

In [ ]:
# Student info
df_students = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Aarav', 'Bhavya', 'Charan', 'Deepika'],
    'Grade': ['A', 'B', 'A', 'B']
})

# Test scores
df_scores = pd.DataFrame({
    'Student_ID': [101, 102, 104, 105],
    'Math_Score': [90, 85, 88, 95],
    'Science_Score': [92, 89, 84, 90]
})

In [ ]:
df_students

   Student_ID     Name Grade
0         101    Aarav     A
1         102   Bhavya     B
2         103   Charan     A
3         104  Deepika     B

In [ ]:
df_scores

   Student_ID  Math_Score  Science_Score
0         101          90             92
1         102          85             89
2         104          88             84
3         105          95             90

## 🔗 Step 3: Merging DataFrames using `merge()`

Default is INNER JOIN on common column (`Student_ID`)

In [ ]:
# Inner join (only matching rows)
pd.merge(df_students, df_scores, on='Student_ID', how='inner')

   Student_ID     Name Grade  Math_Score  Science_Score
0         101    Aarav     A          90             92
1         102   Bhavya     B          85             89
2         104  Deepika     B          88             84

## 🔄 Step 4: Different Types of Joins

In [ ]:
# Left join (keep all students, add matching scores)
pd.merge(df_students, df_scores, on='Student_ID', how='left')

   Student_ID     Name Grade  Math_Score  Science_Score
0         101    Aarav     A        90.0           92.0
1         102   Bhavya     B        85.0           89.0
2         103   Charan     A         NaN            NaN
3         104  Deepika     B        88.0           84.0

In [ ]:
# Right join (keep all scores, add matching student info)
pd.merge(df_students, df_scores, on='Student_ID', how='right')

   Student_ID     Name Grade  Math_Score  Science_Score
0         101    Aarav     A          90             92
1         102   Bhavya     B          85             89
2         104  Deepika     B          88             84
3         105      NaN   NaN          95             90

In [ ]:
# Outer join (keep all rows from both)
pd.merge(df_students, df_scores, on='Student_ID', how='outer')

   Student_ID     Name Grade  Math_Score  Science_Score
0         101    Aarav     A        90.0           92.0
1         102   Bhavya     B        85.0           89.0
2         103   Charan     A         NaN            NaN
3         104  Deepika     B        88.0           84.0
4         105      NaN   NaN        95.0           90.0

## 📦 Step 5: Concatenating DataFrames using `concat()`

Useful when stacking DataFrames vertically (row-wise) or horizontally (column-wise)

In [ ]:
# Vertical stacking (add more student rows)
df_more_students = pd.DataFrame({
    'Student_ID': [106, 107],
    'Name': ['Esha', 'Farhan'],
    'Grade': ['A', 'B']
})

pd.concat([df_students, df_more_students])

   Student_ID     Name Grade
0         101    Aarav     A
1         102   Bhavya     B
2         103   Charan     A
3         104  Deepika     B
0         106     Esha     A
1         107   Farhan     B

In [ ]:
# Horizontal stacking (add more columns side-by-side)
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'C': [5, 6], 'D': [7, 8]})

pd.concat([df1, df2], axis=1)

   A  B  C  D
0  1  3  5  7
1  2  4  6  8

## 📝 Step 7: Practice Questions

1. Do an inner join between student and score tables.
2. Try outer and left joins – which rows are filled with NaN?
3. Merge on both `Student_ID` and `Grade`.
4. Concatenate two DataFrames row-wise.
5. Stack two DataFrames side-by-side (column-wise).
6. Create a dataset ready for ML by merging info + scores.
7. Add a new column “Total_Score” after merging.

In [ ]:
import pandas as pd

# Sample DataFrames
df_students = pd.DataFrame({
    'Student_ID': [101, 102, 103, 104],
    'Name': ['Aarav', 'Bhavya', 'Charan', 'Deepika'],
    'Grade': ['A', 'B', 'A', 'B']
})

df_scores = pd.DataFrame({
    'Student_ID': [101, 102, 104, 105],
    'Score': [88, 77, 91, 83]
})

# 1. Inner Join between student and score tables
inner_join = pd.merge(df_students, df_scores, on='Student_ID', how='inner')
print("1️⃣ Inner Join:\n", inner_join)

# 2. Outer and Left Joins
outer_join = pd.merge(df_students, df_scores, on='Student_ID', how='outer')
left_join = pd.merge(df_students, df_scores, on='Student_ID', how='left')

print("\n2️⃣ Outer Join (NaNs where no match):\n", outer_join)
print("\n2️⃣ Left Join (NaNs for students without scores):\n", left_join)

# 3. Merge on both Student_ID and Grade
# Simulate Grade in df_scores
df_scores_with_grade = pd.DataFrame({
    'Student_ID': [101, 102, 104, 105],
    'Grade': ['A', 'B', 'B', 'C'],
    'Score': [88, 77, 91, 83]
})

merged_on_two = pd.merge(df_students, df_scores_with_grade, on=['Student_ID', 'Grade'], how='inner')
print("\n3️⃣ Merge on Student_ID and Grade:\n", merged_on_two)

# 4. Concatenate two DataFrames row-wise
df_more_students = pd.DataFrame({
    'Student_ID': [106, 107],
    'Name': ['Esha', 'Farhan'],
    'Grade': ['A', 'B']
})
row_concat = pd.concat([df_students, df_more_students], ignore_index=True)
print("\n4️⃣ Row-wise Concatenation:\n", row_concat)

# 5. Stack two DataFrames side-by-side (column-wise)
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'C': [5, 6], 'D': [7, 8]})
col_concat = pd.concat([df1, df2], axis=1)
print("\n5️⃣ Column-wise Concatenation:\n", col_concat)

# 6. Create a dataset ready for ML by merging info + scores
ml_dataset = pd.merge(df_students, df_scores, on='Student_ID', how='inner')

# 7. Add a new column “Total_Score” after merging
ml_dataset['Total_Score'] = ml_dataset['Score']
print("\n6️⃣ & 7️⃣ ML-ready Dataset with Total_Score:\n", ml_dataset)