# 🏏 IPL Data Analysis – Capstone Project

## 🎯 Project Goal
The goal of this project is to analyze IPL (Indian Premier League) matches dataset to uncover trends, patterns, and insights.  

We will use **NumPy & Pandas** for data analysis and generate meaningful insights about teams, toss decisions, venues, and players.
  
This is a beginner-friendly project without machine learning but gives a complete **real-world sports analytics experience**.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("matches.csv")

In [ ]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

## 📊 Dataset Overview
Let’s understand the structure of the dataset.

In [ ]:
df.shape

(1095, 20)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [ ]:
df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [ ]:
df['city'] = df['city'].fillna("Unknown")

In [ ]:
df['player_of_match'] = df['player_of_match'].fillna('No award')

In [ ]:
df['winner'] = df['winner'].fillna("No result")

In [ ]:
df.isnull().sum()

id                    0
season                0
city                  0
date                  0
match_type            0
player_of_match       0
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                0
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [ ]:
df = df.drop(columns=['umpire1', 'umpire2'], errors = 'ignore')

In [ ]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN

## 🔍 Matches per Season

In [ ]:
df['season'].value_counts().sort_index()

season
2007/08    58
2009       57
2009/10    60
2011       73
2012       74
2013       76
2014       60
2015       59
2016       60
2017       59
2018       60
2019       60
2020/21    60
2021       60
2022       74
2023       74
2024       71
Name: count, dtype: int64

## 🏆 Most Successful Teams

In [ ]:
df['winner'].value_counts()

winner
Mumbai Indians                 144
Chennai Super Kings            138
Kolkata Knight Riders          131
Royal Challengers Bangalore    116
Rajasthan Royals               112
Kings XI Punjab                 88
Sunrisers Hyderabad             88
Delhi Daredevils                67
Delhi Capitals                  48
Deccan Chargers                 29
Gujarat Titans                  28
Punjab Kings                    24
Lucknow Super Giants            24
Gujarat Lions                   13
Pune Warriors                   12
Rising Pune Supergiant          10
Royal Challengers Bengaluru      7
Kochi Tuskers Kerala             6
No result                        5
Rising Pune Supergiants          5
Name: count, dtype: int64

## How many matches ended with "No Result"?

In [ ]:
(df['winner'] == "No result").sum()

np.int64(5)

## 🎲 Toss Decisions – Does winning toss matter?

In [ ]:
toss_match = (df['toss_winner'] == df['winner']).sum()
toss_match

np.int64(554)

In [ ]:
total_matches = df.shape[0]
round((toss_match/total_matches)*100)

51

## ⭐ Player of the Match Analysis

In [ ]:
df['player_of_match'].value_counts().head(10)

player_of_match
AB de Villiers    25
CH Gayle          22
RG Sharma         19
DA Warner         18
V Kohli           18
MS Dhoni          17
RA Jadeja         16
YK Pathan         16
SR Watson         16
AD Russell        15
Name: count, dtype: int64

## What are the most common toss decisions (bat or field)?

In [ ]:
df['toss_decision'].value_counts()

toss_decision
field    704
bat      391
Name: count, dtype: int64

## Which teams are most successful at a particular venue? (Example: M Chinnaswamy Stadium)

In [ ]:
venue = "Wankhede Stadium"
venue_wins = df[df['venue'] == venue]['winner'].value_counts()
venue_wins

winner
Mumbai Indians                 42
Chennai Super Kings             7
Kings XI Punjab                 5
Rajasthan Royals                4
Royal Challengers Bangalore     3
Rising Pune Supergiant          2
Delhi Daredevils                2
Deccan Chargers                 1
Kochi Tuskers Kerala            1
Kolkata Knight Riders           1
Pune Warriors                   1
Rising Pune Supergiants         1
Gujarat Lions                   1
Sunrisers Hyderabad             1
Delhi Capitals                  1
Name: count, dtype: int64

## Which matches ended with the smallest and largest margins?

In [ ]:
df[df['result'] == 'runs'].sort_values(by='result_margin', ascending=False).head(1)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method
620,1082635,2017,Delhi,2017-05-06,League,LMP Simmons,Feroz Shah Kotla,Delhi Daredevils,Mumbai Indians,Delhi Daredevils,field,Mumbai Indians,runs,146.0,213.0,20.0,N,NaN

In [ ]:
df[df['result'] == 'wickets'].sort_values(by='result_margin', ascending=False).head(1)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method
12,335994,2007/08,Mumbai,2008-04-27,League,AC Gilchrist,Dr DY Patil Sports Academy,Mumbai Indians,Deccan Chargers,Deccan Chargers,field,Deccan Chargers,wickets,10.0,155.0,20.0,N,NaN

In [ ]:
df[df['result'] == 'runs'].sort_values(by='result_margin', ascending=True).head(1)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method
44,336028,2007/08,Mumbai,2008-05-21,League,SE Marsh,Wankhede Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,field,Kings XI Punjab,runs,1.0,190.0,20.0,N,NaN

In [ ]:
df[df['result'] == 'wickets'].sort_values(by='result_margin', ascending=True).head(1)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method
642,1136567,2018,Hyderabad,2018-04-12,League,Rashid Khan,Rajiv Gandhi International Stadium,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,1.0,148.0,20.0,N,NaN

## How many matches were decided by Duckworth-Lewis (D/L) method?

In [ ]:
df['method'].notnull().sum()

np.int64(21)

## Which team won the most finals?

In [ ]:
df[df['match_type'] == 'Final']['winner'].value_counts()

winner
Chennai Super Kings      5
Mumbai Indians           5
Kolkata Knight Riders    3
Deccan Chargers          1
Rajasthan Royals         1
Sunrisers Hyderabad      1
Gujarat Titans           1
Name: count, dtype: int64

# 📌 Key Insights & Conclusion

1. **Matches per Season:** IPL has grown across seasons with varying number of matches.  
2. **Most Successful Teams:** Mumbai Indians and Chennai Super Kings have the highest wins overall.  
3. **Player of the Match:** Legends like AB de Villiers, MS Dhoni, and Chris Gayle have won the most awards.  
4. **No Result Matches:** A few matches ended without results due to rain.  
5. **Toss Impact:** Winning the toss gives a slight advantage but is not a guarantee of winning.  
6. **Venues:** Some stadiums like Wankhede and Eden Gardens host maximum matches and show home team dominance.  
7. **Margins:** IPL has seen nail-biting close wins as well as massive victories.  
8. **D/L Method:** Rarely used but important in rain-affected matches.  
9. **Final Winners:** Mumbai Indians and CSK dominate IPL finals historically.  

This project shows that even with **just Pandas and Numpy**, we can extract powerful insights from a sports dataset.  
It is a great beginner-friendly data analysis capstone project.